### ISSUE TITLE
 npm install

### ISSUE THREAD

**Issue by zanjs** [arrking/austack-core#249]
> austack@0.0.0 postinstall E:\zan\www\node\austack-core
> ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update

'.' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! austack@0.0.0 postinstall: `./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the austack@0.0.0 postinstall script './node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update'.
npm ERR! This is most likely a problem with the austack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update
npm ERR! You can get their info via:
npm ERR!     npm owner ls austack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\zan\www\node\austack-core\npm-debug.log

**Comment by Samurais** [comment]
这是因为npm包安装不稳定，以前也遇到过。解决办法：
（1）多执行两边，最好能翻墙。
（2）手动安装

```
cd ./node_modules/gulp-protractor
npm install protractor
```

另外，这个包是测试时使用的，如果执行 npm start, 服务应该可以运行的。

**Comment by zanjs** [comment]
npm WARN package.json Dependency 'gulp-protractor' exists in both dependencies and devDependencies, using 'gulp-protractor@^1.0.0' from dependencies

**Comment by zanjs** [comment]
npm start 运行报错了 安装包少好多 呜呜

**Comment by zanjs** [comment]
package.json 里面的包有些老了 可以把包都更新到当前最新版本吗  运行应该不会出错把

**Comment by zanjs** [comment]
Administrator@WIN-9PH4ISN44NM MINGW64 /e/zan/www/node/austack-core (develop)
$ touch .env

Administrator@WIN-9PH4ISN44NM MINGW64 /e/zan/www/node/austack-core (develop)
$ npm start

> austack@0.0.0 start E:\zan\www\node\austack-core
> node bin/server.js

E:\zan\www\node\austack-core\dist
E:\zan\www\node\austack-core\dist E:\zan\www\node\austack-core\server\public
Wed, 21 Oct 2015 09:23:41 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at server\config\express.js:57:11
2015-10-21T17:23:41+0800 E:\zan\www\node\austack-core\server\lib\sms\index.js:11
 <debug> Initialize SMS Service with weimi {"uid":"lmf8FDhlAHHB","pas":"r2z36xbh","cid":"Zh07NWBGgr1r"}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:9001
    at Object.exports._errnoException (util.js:849:11)
    at exports._exceptionWithHostPort (util.js:872:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at doNTCallback3 (node.js:441:9)
    at process._tickDomainCallback (node.js:388:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:118:18)
    at node.js:952:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! austack@0.0.0 start: `node bin/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the austack@0.0.0 start script 'node bin/server.js'.
npm ERR! This is most likely a problem with the austack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls austack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\zan\www\node\austack-core\npm-debug.log

**Comment by hailiang-wang** [comment]
Sorry, I get time now to handle it.
